-- This file is automatically generated, do not change it!
module Installation where

compilerName :: String
compilerName = "KiCS2 Curry -> Haskell Compiler"

installDir :: String
installDir = "/home/spalac24/EAFIT/PP/paradigmas_de_programacion/curry/kics2-0.3.0"

majorVersion :: Int
majorVersion = 0

minorVersion :: Int
minorVersion = 3

revisionVersion :: Int
revisionVersion = 0

compilerDate :: String
compilerDate = "2013-07-25"

installDate :: String
installDate = "Wed Sep  4 00:50:14 COT 2013"

runtime :: String
runtime = "ghc"

runtimeMajor :: Int
runtimeMajor = 7

runtimeMinor :: Int
runtimeMinor = 4

ghcExec :: String
ghcExec = "\"/usr/bin/ghc\""

ghcOptions :: String
ghcOptions = "-no-user-package-conf -package-conf /home/spalac24/EAFIT/PP/paradigmas_de_programacion/curry/kics2-0.3.0/pkg/kics2.conf.d"

installGlobal :: Bool
installGlobal = True
