-- This file is automatically generated, do not change it!
module Installation where

compilerName :: String
compilerName = "KiCS2 Curry -> Haskell Compiler"

installDir :: String
installDir = "/home/spalac24/EAFIT/2013-1/PARADIGMAS-DE-PROGRAMACION/curry/kics2/kics2-0.2.4"

majorVersion :: Int
majorVersion = 0

minorVersion :: Int
minorVersion = 2

revisionVersion :: Int
revisionVersion = 4

compilerDate :: String
compilerDate = "2013-03-20"

installDate :: String
installDate = "Thu May  9 16:59:47 COT 2013"

runtime :: String
runtime = "ghc"

runtimeMajor :: Int
runtimeMajor = 7

runtimeMinor :: Int
runtimeMinor = 4

ghcExec :: String
ghcExec = "\"/usr/bin/ghc\" -no-user-package-conf -package-conf \"/home/spalac24/.ghc/x86_64-linux-7.4.2/package.conf.d\""

ghcOptions :: String
ghcOptions = ""

installGlobal :: Bool
installGlobal = True
